// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: account.proto

package accountpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterNasabahRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NomorIdentitas string                 `protobuf:"bytes,1,opt,name=nomor_identitas,json=nomorIdentitas,proto3" json:"nomor_identitas,omitempty"`
	Nama           string                 `protobuf:"bytes,2,opt,name=nama,proto3" json:"nama,omitempty"`
	NoHp           string                 `protobuf:"bytes,3,opt,name=no_hp,json=noHp,proto3" json:"no_hp,omitempty"`
	Email          string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Pekerjaan      string                 `protobuf:"bytes,5,opt,name=pekerjaan,proto3" json:"pekerjaan,omitempty"`
	AlamatNasabah  string                 `protobuf:"bytes,6,opt,name=alamat_nasabah,json=alamatNasabah,proto3" json:"alamat_nasabah,omitempty"`
	Pin            string                 `protobuf:"bytes,7,opt,name=pin,proto3" json:"pin,omitempty"`
	SetoranAwal    int64                  `protobuf:"varint,8,opt,name=setoran_awal,json=setoranAwal,proto3" json:"setoran_awal,omitempty"`
	TipeNasabah    string                 `protobuf:"bytes,9,opt,name=tipe_nasabah,json=tipeNasabah,proto3" json:"tipe_nasabah,omitempty"`
	Npwp           string                 `protobuf:"bytes,10,opt,name=npwp,proto3" json:"npwp,omitempty"`
	AlamatKantor   string                 `protobuf:"bytes,11,opt,name=alamat_kantor,json=alamatKantor,proto3" json:"alamat_kantor,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterNasabahRequest) Reset() {
	*x = RegisterNasabahRequest{}
	mi := &file_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNasabahRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNasabahRequest) ProtoMessage() {}

func (x *RegisterNasabahRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNasabahRequest.ProtoReflect.Descriptor instead.
func (*RegisterNasabahRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterNasabahRequest) GetNomorIdentitas() string {
	if x != nil {
		return x.NomorIdentitas
	}
	return ""
}

func (x *RegisterNasabahRequest) GetNama() string {
	if x != nil {
		return x.Nama
	}
	return ""
}

func (x *RegisterNasabahRequest) GetNoHp() string {
	if x != nil {
		return x.NoHp
	}
	return ""
}

func (x *RegisterNasabahRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterNasabahRequest) GetPekerjaan() string {
	if x != nil {
		return x.Pekerjaan
	}
	return ""
}

func (x *RegisterNasabahRequest) GetAlamatNasabah() string {
	if x != nil {
		return x.AlamatNasabah
	}
	return ""
}

func (x *RegisterNasabahRequest) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

func (x *RegisterNasabahRequest) GetSetoranAwal() int64 {
	if x != nil {
		return x.SetoranAwal
	}
	return 0
}

func (x *RegisterNasabahRequest) GetTipeNasabah() string {
	if x != nil {
		return x.TipeNasabah
	}
	return ""
}

func (x *RegisterNasabahRequest) GetNpwp() string {
	if x != nil {
		return x.Npwp
	}
	return ""
}

func (x *RegisterNasabahRequest) GetAlamatKantor() string {
	if x != nil {
		return x.AlamatKantor
	}
	return ""
}

type RegisterNasabahResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nama          string                 `protobuf:"bytes,1,opt,name=nama,proto3" json:"nama,omitempty"`
	NoRek         string                 `protobuf:"bytes,2,opt,name=no_rek,json=noRek,proto3" json:"no_rek,omitempty"`
	Saldo         int64                  `protobuf:"varint,3,opt,name=saldo,proto3" json:"saldo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNasabahResponse) Reset() {
	*x = RegisterNasabahResponse{}
	mi := &file_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNasabahResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNasabahResponse) ProtoMessage() {}

func (x *RegisterNasabahResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNasabahResponse.ProtoReflect.Descriptor instead.
func (*RegisterNasabahResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterNasabahResponse) GetNama() string {
	if x != nil {
		return x.Nama
	}
	return ""
}

func (x *RegisterNasabahResponse) GetNoRek() string {
	if x != nil {
		return x.NoRek
	}
	return ""
}

func (x *RegisterNasabahResponse) GetSaldo() int64 {
	if x != nil {
		return x.Saldo
	}
	return 0
}

type VerifyPINRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoRek         string                 `protobuf:"bytes,1,opt,name=no_rek,json=noRek,proto3" json:"no_rek,omitempty"`
	Pin           string                 `protobuf:"bytes,2,opt,name=pin,proto3" json:"pin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPINRequest) Reset() {
	*x = VerifyPINRequest{}
	mi := &file_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPINRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPINRequest) ProtoMessage() {}

func (x *VerifyPINRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPINRequest.ProtoReflect.Descriptor instead.
func (*VerifyPINRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyPINRequest) GetNoRek() string {
	if x != nil {
		return x.NoRek
	}
	return ""
}

func (x *VerifyPINRequest) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

type VerifyPINResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	NasabahId     string                 `protobuf:"bytes,2,opt,name=nasabah_id,json=nasabahId,proto3" json:"nasabah_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPINResponse) Reset() {
	*x = VerifyPINResponse{}
	mi := &file_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPINResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPINResponse) ProtoMessage() {}

func (x *VerifyPINResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPINResponse.ProtoReflect.Descriptor instead.
func (*VerifyPINResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyPINResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *VerifyPINResponse) GetNasabahId() string {
	if x != nil {
		return x.NasabahId
	}
	return ""
}

func (x *VerifyPINResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAccountDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoRek         string                 `protobuf:"bytes,1,opt,name=no_rek,json=noRek,proto3" json:"no_rek,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountDetailRequest) Reset() {
	*x = GetAccountDetailRequest{}
	mi := &file_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountDetailRequest) ProtoMessage() {}

func (x *GetAccountDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountDetailRequest.ProtoReflect.Descriptor instead.
func (*GetAccountDetailRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{4}
}

func (x *GetAccountDetailRequest) GetNoRek() string {
	if x != nil {
		return x.NoRek
	}
	return ""
}

type GetAccountDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NasabahId     string                 `protobuf:"bytes,1,opt,name=nasabah_id,json=nasabahId,proto3" json:"nasabah_id,omitempty"`
	NoRek         string                 `protobuf:"bytes,2,opt,name=no_rek,json=noRek,proto3" json:"no_rek,omitempty"`
	Nama          string                 `protobuf:"bytes,3,opt,name=nama,proto3" json:"nama,omitempty"`
	Saldo         int64                  `protobuf:"varint,4,opt,name=saldo,proto3" json:"saldo,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	TipeNasabah   string                 `protobuf:"bytes,6,opt,name=tipe_nasabah,json=tipeNasabah,proto3" json:"tipe_nasabah,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountDetailResponse) Reset() {
	*x = GetAccountDetailResponse{}
	mi := &file_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountDetailResponse) ProtoMessage() {}

func (x *GetAccountDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountDetailResponse.ProtoReflect.Descriptor instead.
func (*GetAccountDetailResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{5}
}

func (x *GetAccountDetailResponse) GetNasabahId() string {
	if x != nil {
		return x.NasabahId
	}
	return ""
}

func (x *GetAccountDetailResponse) GetNoRek() string {
	if x != nil {
		return x.NoRek
	}
	return ""
}

func (x *GetAccountDetailResponse) GetNama() string {
	if x != nil {
		return x.Nama
	}
	return ""
}

func (x *GetAccountDetailResponse) GetSaldo() int64 {
	if x != nil {
		return x.Saldo
	}
	return 0
}

func (x *GetAccountDetailResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetAccountDetailResponse) GetTipeNasabah() string {
	if x != nil {
		return x.TipeNasabah
	}
	return ""
}

var File_account_proto protoreflect.FileDescriptor

const file_account_proto_rawDesc = "" +
	"\n" +
	"\raccount.proto\x12\aaccount\"\xd6\x02\n" +
	"\x16RegisterNasabahRequest\x12'\n" +
	"\x0fnomor_identitas\x18\x01 \x01(\tR\x0enomorIdentitas\x12\x12\n" +
	"\x04nama\x18\x02 \x01(\tR\x04nama\x12\x13\n" +
	"\x05no_hp\x18\x03 \x01(\tR\x04noHp\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1c\n" +
	"\tpekerjaan\x18\x05 \x01(\tR\tpekerjaan\x12%\n" +
	"\x0ealamat_nasabah\x18\x06 \x01(\tR\ralamatNasabah\x12\x10\n" +
	"\x03pin\x18\a \x01(\tR\x03pin\x12!\n" +
	"\fsetoran_awal\x18\b \x01(\x03R\vsetoranAwal\x12!\n" +
	"\ftipe_nasabah\x18\t \x01(\tR\vtipeNasabah\x12\x12\n" +
	"\x04npwp\x18\n" +
	" \x01(\tR\x04npwp\x12#\n" +
	"\ralamat_kantor\x18\v \x01(\tR\falamatKantor\"Z\n" +
	"\x17RegisterNasabahResponse\x12\x12\n" +
	"\x04nama\x18\x01 \x01(\tR\x04nama\x12\x15\n" +
	"\x06no_rek\x18\x02 \x01(\tR\x05noRek\x12\x14\n" +
	"\x05saldo\x18\x03 \x01(\x03R\x05saldo\";\n" +
	"\x10VerifyPINRequest\x12\x15\n" +
	"\x06no_rek\x18\x01 \x01(\tR\x05noRek\x12\x10\n" +
	"\x03pin\x18\x02 \x01(\tR\x03pin\"g\n" +
	"\x11VerifyPINResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12\x1d\n" +
	"\n" +
	"nasabah_id\x18\x02 \x01(\tR\tnasabahId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"0\n" +
	"\x17GetAccountDetailRequest\x12\x15\n" +
	"\x06no_rek\x18\x01 \x01(\tR\x05noRek\"\xb5\x01\n" +
	"\x18GetAccountDetailResponse\x12\x1d\n" +
	"\n" +
	"nasabah_id\x18\x01 \x01(\tR\tnasabahId\x12\x15\n" +
	"\x06no_rek\x18\x02 \x01(\tR\x05noRek\x12\x12\n" +
	"\x04nama\x18\x03 \x01(\tR\x04nama\x12\x14\n" +
	"\x05saldo\x18\x04 \x01(\x03R\x05saldo\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12!\n" +
	"\ftipe_nasabah\x18\x06 \x01(\tR\vtipeNasabah2\x83\x02\n" +
	"\x0eAccountService\x12T\n" +
	"\x0fRegisterNasabah\x12\x1f.account.RegisterNasabahRequest\x1a .account.RegisterNasabahResponse\x12B\n" +
	"\tVerifyPIN\x12\x19.account.VerifyPINRequest\x1a\x1a.account.VerifyPINResponse\x12W\n" +
	"\x10GetAccountDetail\x12 .account.GetAccountDetailRequest\x1a!.account.GetAccountDetailResponseB\x0eZ\f./;accountpbb\x06proto3"

var (
	file_account_proto_rawDescOnce sync.Once
	file_account_proto_rawDescData []byte
)

func file_account_proto_rawDescGZIP() []byte {
	file_account_proto_rawDescOnce.Do(func() {
		file_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_proto_rawDesc), len(file_account_proto_rawDesc)))
	})
	return file_account_proto_rawDescData
}

var file_account_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_account_proto_goTypes = []any{
	(*RegisterNasabahRequest)(nil),   // 0: account.RegisterNasabahRequest
	(*RegisterNasabahResponse)(nil),  // 1: account.RegisterNasabahResponse
	(*VerifyPINRequest)(nil),         // 2: account.VerifyPINRequest
	(*VerifyPINResponse)(nil),        // 3: account.VerifyPINResponse
	(*GetAccountDetailRequest)(nil),  // 4: account.GetAccountDetailRequest
	(*GetAccountDetailResponse)(nil), // 5: account.GetAccountDetailResponse
}
var file_account_proto_depIdxs = []int32{
	0, // 0: account.AccountService.RegisterNasabah:input_type -> account.RegisterNasabahRequest
	2, // 1: account.AccountService.VerifyPIN:input_type -> account.VerifyPINRequest
	4, // 2: account.AccountService.GetAccountDetail:input_type -> account.GetAccountDetailRequest
	1, // 3: account.AccountService.RegisterNasabah:output_type -> account.RegisterNasabahResponse
	3, // 4: account.AccountService.VerifyPIN:output_type -> account.VerifyPINResponse
	5, // 5: account.AccountService.GetAccountDetail:output_type -> account.GetAccountDetailResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_account_proto_init() }
func file_account_proto_init() {
	if File_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_proto_rawDesc), len(file_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_proto_goTypes,
		DependencyIndexes: file_account_proto_depIdxs,
		MessageInfos:      file_account_proto_msgTypes,
	}.Build()
	File_account_proto = out.File
	file_account_proto_goTypes = nil
	file_account_proto_depIdxs = nil
}
