// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: account.proto

package accountpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountService_RegisterNasabah_FullMethodName  = "/account.AccountService/RegisterNasabah"
	AccountService_VerifyPIN_FullMethodName        = "/account.AccountService/VerifyPIN"
	AccountService_GetAccountDetail_FullMethodName = "/account.AccountService/GetAccountDetail"
)

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountServiceClient interface {
	RegisterNasabah(ctx context.Context, in *RegisterNasabahRequest, opts ...grpc.CallOption) (*RegisterNasabahResponse, error)
	VerifyPIN(ctx context.Context, in *VerifyPINRequest, opts ...grpc.CallOption) (*VerifyPINResponse, error)
	GetAccountDetail(ctx context.Context, in *GetAccountDetailRequest, opts ...grpc.CallOption) (*GetAccountDetailResponse, error)
}

type accountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountServiceClient(cc grpc.ClientConnInterface) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) RegisterNasabah(ctx context.Context, in *RegisterNasabahRequest, opts ...grpc.CallOption) (*RegisterNasabahResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNasabahResponse)
	err := c.cc.Invoke(ctx, AccountService_RegisterNasabah_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) VerifyPIN(ctx context.Context, in *VerifyPINRequest, opts ...grpc.CallOption) (*VerifyPINResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyPINResponse)
	err := c.cc.Invoke(ctx, AccountService_VerifyPIN_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetAccountDetail(ctx context.Context, in *GetAccountDetailRequest, opts ...grpc.CallOption) (*GetAccountDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccountDetailResponse)
	err := c.cc.Invoke(ctx, AccountService_GetAccountDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
// All implementations must embed UnimplementedAccountServiceServer
// for forward compatibility.
type AccountServiceServer interface {
	RegisterNasabah(context.Context, *RegisterNasabahRequest) (*RegisterNasabahResponse, error)
	VerifyPIN(context.Context, *VerifyPINRequest) (*VerifyPINResponse, error)
	GetAccountDetail(context.Context, *GetAccountDetailRequest) (*GetAccountDetailResponse, error)
	mustEmbedUnimplementedAccountServiceServer()
}

// UnimplementedAccountServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountServiceServer struct{}

func (UnimplementedAccountServiceServer) RegisterNasabah(context.Context, *RegisterNasabahRequest) (*RegisterNasabahResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNasabah not implemented")
}
func (UnimplementedAccountServiceServer) VerifyPIN(context.Context, *VerifyPINRequest) (*VerifyPINResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyPIN not implemented")
}
func (UnimplementedAccountServiceServer) GetAccountDetail(context.Context, *GetAccountDetailRequest) (*GetAccountDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccountDetail not implemented")
}
func (UnimplementedAccountServiceServer) mustEmbedUnimplementedAccountServiceServer() {}
func (UnimplementedAccountServiceServer) testEmbeddedByValue()                        {}

// UnsafeAccountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountServiceServer will
// result in compilation errors.
type UnsafeAccountServiceServer interface {
	mustEmbedUnimplementedAccountServiceServer()
}

func RegisterAccountServiceServer(s grpc.ServiceRegistrar, srv AccountServiceServer) {
	// If the following call panics, it indicates UnimplementedAccountServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountService_ServiceDesc, srv)
}

func _AccountService_RegisterNasabah_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNasabahRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).RegisterNasabah(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_RegisterNasabah_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).RegisterNasabah(ctx, req.(*RegisterNasabahRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_VerifyPIN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyPINRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).VerifyPIN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_VerifyPIN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).VerifyPIN(ctx, req.(*VerifyPINRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetAccountDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetAccountDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetAccountDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetAccountDetail(ctx, req.(*GetAccountDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountService_ServiceDesc is the grpc.ServiceDesc for AccountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "account.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNasabah",
			Handler:    _AccountService_RegisterNasabah_Handler,
		},
		{
			MethodName: "VerifyPIN",
			Handler:    _AccountService_VerifyPIN_Handler,
		},
		{
			MethodName: "GetAccountDetail",
			Handler:    _AccountService_GetAccountDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}
