// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: transaction.proto

package transactionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CashDepositRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoRek         string                 `protobuf:"bytes,1,opt,name=no_rek,json=noRek,proto3" json:"no_rek,omitempty"`
	Nominal       int64                  `protobuf:"varint,2,opt,name=nominal,proto3" json:"nominal,omitempty"`
	Pin           string                 `protobuf:"bytes,3,opt,name=pin,proto3" json:"pin,omitempty"`
	Keterangan    string                 `protobuf:"bytes,4,opt,name=keterangan,proto3" json:"keterangan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashDepositRequest) Reset() {
	*x = CashDepositRequest{}
	mi := &file_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashDepositRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashDepositRequest) ProtoMessage() {}

func (x *CashDepositRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashDepositRequest.ProtoReflect.Descriptor instead.
func (*CashDepositRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *CashDepositRequest) GetNoRek() string {
	if x != nil {
		return x.NoRek
	}
	return ""
}

func (x *CashDepositRequest) GetNominal() int64 {
	if x != nil {
		return x.Nominal
	}
	return 0
}

func (x *CashDepositRequest) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

func (x *CashDepositRequest) GetKeterangan() string {
	if x != nil {
		return x.Keterangan
	}
	return ""
}

type CashDepositResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransaksiId   string                 `protobuf:"bytes,1,opt,name=transaksi_id,json=transaksiId,proto3" json:"transaksi_id,omitempty"`
	NoRek         string                 `protobuf:"bytes,2,opt,name=no_rek,json=noRek,proto3" json:"no_rek,omitempty"`
	TotalSaldo    int64                  `protobuf:"varint,3,opt,name=total_saldo,json=totalSaldo,proto3" json:"total_saldo,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashDepositResponse) Reset() {
	*x = CashDepositResponse{}
	mi := &file_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashDepositResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashDepositResponse) ProtoMessage() {}

func (x *CashDepositResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashDepositResponse.ProtoReflect.Descriptor instead.
func (*CashDepositResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *CashDepositResponse) GetTransaksiId() string {
	if x != nil {
		return x.TransaksiId
	}
	return ""
}

func (x *CashDepositResponse) GetNoRek() string {
	if x != nil {
		return x.NoRek
	}
	return ""
}

func (x *CashDepositResponse) GetTotalSaldo() int64 {
	if x != nil {
		return x.TotalSaldo
	}
	return 0
}

func (x *CashDepositResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CashWithdrawalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoRek         string                 `protobuf:"bytes,1,opt,name=no_rek,json=noRek,proto3" json:"no_rek,omitempty"`
	Nominal       int64                  `protobuf:"varint,2,opt,name=nominal,proto3" json:"nominal,omitempty"`
	Pin           string                 `protobuf:"bytes,3,opt,name=pin,proto3" json:"pin,omitempty"`
	Keterangan    string                 `protobuf:"bytes,4,opt,name=keterangan,proto3" json:"keterangan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashWithdrawalRequest) Reset() {
	*x = CashWithdrawalRequest{}
	mi := &file_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashWithdrawalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashWithdrawalRequest) ProtoMessage() {}

func (x *CashWithdrawalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashWithdrawalRequest.ProtoReflect.Descriptor instead.
func (*CashWithdrawalRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *CashWithdrawalRequest) GetNoRek() string {
	if x != nil {
		return x.NoRek
	}
	return ""
}

func (x *CashWithdrawalRequest) GetNominal() int64 {
	if x != nil {
		return x.Nominal
	}
	return 0
}

func (x *CashWithdrawalRequest) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

func (x *CashWithdrawalRequest) GetKeterangan() string {
	if x != nil {
		return x.Keterangan
	}
	return ""
}

type CashWithdrawalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransaksiId   string                 `protobuf:"bytes,1,opt,name=transaksi_id,json=transaksiId,proto3" json:"transaksi_id,omitempty"`
	NoRek         string                 `protobuf:"bytes,2,opt,name=no_rek,json=noRek,proto3" json:"no_rek,omitempty"`
	TotalSaldo    int64                  `protobuf:"varint,3,opt,name=total_saldo,json=totalSaldo,proto3" json:"total_saldo,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashWithdrawalResponse) Reset() {
	*x = CashWithdrawalResponse{}
	mi := &file_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashWithdrawalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashWithdrawalResponse) ProtoMessage() {}

func (x *CashWithdrawalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashWithdrawalResponse.ProtoReflect.Descriptor instead.
func (*CashWithdrawalResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *CashWithdrawalResponse) GetTransaksiId() string {
	if x != nil {
		return x.TransaksiId
	}
	return ""
}

func (x *CashWithdrawalResponse) GetNoRek() string {
	if x != nil {
		return x.NoRek
	}
	return ""
}

func (x *CashWithdrawalResponse) GetTotalSaldo() int64 {
	if x != nil {
		return x.TotalSaldo
	}
	return 0
}

func (x *CashWithdrawalResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoRek         string                 `protobuf:"bytes,1,opt,name=no_rek,json=noRek,proto3" json:"no_rek,omitempty"`
	Pin           string                 `protobuf:"bytes,2,opt,name=pin,proto3" json:"pin,omitempty"`
	NoRekTujuan   string                 `protobuf:"bytes,3,opt,name=no_rek_tujuan,json=noRekTujuan,proto3" json:"no_rek_tujuan,omitempty"`
	Nominal       int64                  `protobuf:"varint,4,opt,name=nominal,proto3" json:"nominal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *TransferRequest) GetNoRek() string {
	if x != nil {
		return x.NoRek
	}
	return ""
}

func (x *TransferRequest) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

func (x *TransferRequest) GetNoRekTujuan() string {
	if x != nil {
		return x.NoRekTujuan
	}
	return ""
}

func (x *TransferRequest) GetNominal() int64 {
	if x != nil {
		return x.Nominal
	}
	return 0
}

type TransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransaksiId   string                 `protobuf:"bytes,1,opt,name=transaksi_id,json=transaksiId,proto3" json:"transaksi_id,omitempty"`
	SisaSaldo     int64                  `protobuf:"varint,2,opt,name=sisa_saldo,json=sisaSaldo,proto3" json:"sisa_saldo,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *TransferResponse) GetTransaksiId() string {
	if x != nil {
		return x.TransaksiId
	}
	return ""
}

func (x *TransferResponse) GetSisaSaldo() int64 {
	if x != nil {
		return x.SisaSaldo
	}
	return 0
}

func (x *TransferResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GajiItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoRekKaryawan string                 `protobuf:"bytes,1,opt,name=no_rek_karyawan,json=noRekKaryawan,proto3" json:"no_rek_karyawan,omitempty"`
	NominalGaji   int64                  `protobuf:"varint,2,opt,name=nominal_gaji,json=nominalGaji,proto3" json:"nominal_gaji,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GajiItem) Reset() {
	*x = GajiItem{}
	mi := &file_transaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GajiItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GajiItem) ProtoMessage() {}

func (x *GajiItem) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GajiItem.ProtoReflect.Descriptor instead.
func (*GajiItem) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{6}
}

func (x *GajiItem) GetNoRekKaryawan() string {
	if x != nil {
		return x.NoRekKaryawan
	}
	return ""
}

func (x *GajiItem) GetNominalGaji() int64 {
	if x != nil {
		return x.NominalGaji
	}
	return 0
}

type BatchDepositGajiRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NoRekPerusahaan string                 `protobuf:"bytes,1,opt,name=no_rek_perusahaan,json=noRekPerusahaan,proto3" json:"no_rek_perusahaan,omitempty"`
	NamaPerusahaan  string                 `protobuf:"bytes,2,opt,name=nama_perusahaan,json=namaPerusahaan,proto3" json:"nama_perusahaan,omitempty"`
	PinPerusahaan   string                 `protobuf:"bytes,3,opt,name=pin_perusahaan,json=pinPerusahaan,proto3" json:"pin_perusahaan,omitempty"`
	DaftarGaji      []*GajiItem            `protobuf:"bytes,4,rep,name=daftar_gaji,json=daftarGaji,proto3" json:"daftar_gaji,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BatchDepositGajiRequest) Reset() {
	*x = BatchDepositGajiRequest{}
	mi := &file_transaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDepositGajiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDepositGajiRequest) ProtoMessage() {}

func (x *BatchDepositGajiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDepositGajiRequest.ProtoReflect.Descriptor instead.
func (*BatchDepositGajiRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{7}
}

func (x *BatchDepositGajiRequest) GetNoRekPerusahaan() string {
	if x != nil {
		return x.NoRekPerusahaan
	}
	return ""
}

func (x *BatchDepositGajiRequest) GetNamaPerusahaan() string {
	if x != nil {
		return x.NamaPerusahaan
	}
	return ""
}

func (x *BatchDepositGajiRequest) GetPinPerusahaan() string {
	if x != nil {
		return x.PinPerusahaan
	}
	return ""
}

func (x *BatchDepositGajiRequest) GetDaftarGaji() []*GajiItem {
	if x != nil {
		return x.DaftarGaji
	}
	return nil
}

type BatchDepositGajiResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	TotalDiproses   int32                  `protobuf:"varint,2,opt,name=total_diproses,json=totalDiproses,proto3" json:"total_diproses,omitempty"`
	TotalDanaKeluar int64                  `protobuf:"varint,3,opt,name=total_dana_keluar,json=totalDanaKeluar,proto3" json:"total_dana_keluar,omitempty"`
	Message         string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BatchDepositGajiResponse) Reset() {
	*x = BatchDepositGajiResponse{}
	mi := &file_transaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDepositGajiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDepositGajiResponse) ProtoMessage() {}

func (x *BatchDepositGajiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDepositGajiResponse.ProtoReflect.Descriptor instead.
func (*BatchDepositGajiResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{8}
}

func (x *BatchDepositGajiResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BatchDepositGajiResponse) GetTotalDiproses() int32 {
	if x != nil {
		return x.TotalDiproses
	}
	return 0
}

func (x *BatchDepositGajiResponse) GetTotalDanaKeluar() int64 {
	if x != nil {
		return x.TotalDanaKeluar
	}
	return 0
}

func (x *BatchDepositGajiResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_transaction_proto protoreflect.FileDescriptor

const file_transaction_proto_rawDesc = "" +
	"\n" +
	"\x11transaction.proto\x12\vtransaction\"w\n" +
	"\x12CashDepositRequest\x12\x15\n" +
	"\x06no_rek\x18\x01 \x01(\tR\x05noRek\x12\x18\n" +
	"\anominal\x18\x02 \x01(\x03R\anominal\x12\x10\n" +
	"\x03pin\x18\x03 \x01(\tR\x03pin\x12\x1e\n" +
	"\n" +
	"keterangan\x18\x04 \x01(\tR\n" +
	"keterangan\"\x8a\x01\n" +
	"\x13CashDepositResponse\x12!\n" +
	"\ftransaksi_id\x18\x01 \x01(\tR\vtransaksiId\x12\x15\n" +
	"\x06no_rek\x18\x02 \x01(\tR\x05noRek\x12\x1f\n" +
	"\vtotal_saldo\x18\x03 \x01(\x03R\n" +
	"totalSaldo\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"z\n" +
	"\x15CashWithdrawalRequest\x12\x15\n" +
	"\x06no_rek\x18\x01 \x01(\tR\x05noRek\x12\x18\n" +
	"\anominal\x18\x02 \x01(\x03R\anominal\x12\x10\n" +
	"\x03pin\x18\x03 \x01(\tR\x03pin\x12\x1e\n" +
	"\n" +
	"keterangan\x18\x04 \x01(\tR\n" +
	"keterangan\"\x8d\x01\n" +
	"\x16CashWithdrawalResponse\x12!\n" +
	"\ftransaksi_id\x18\x01 \x01(\tR\vtransaksiId\x12\x15\n" +
	"\x06no_rek\x18\x02 \x01(\tR\x05noRek\x12\x1f\n" +
	"\vtotal_saldo\x18\x03 \x01(\x03R\n" +
	"totalSaldo\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"x\n" +
	"\x0fTransferRequest\x12\x15\n" +
	"\x06no_rek\x18\x01 \x01(\tR\x05noRek\x12\x10\n" +
	"\x03pin\x18\x02 \x01(\tR\x03pin\x12\"\n" +
	"\rno_rek_tujuan\x18\x03 \x01(\tR\vnoRekTujuan\x12\x18\n" +
	"\anominal\x18\x04 \x01(\x03R\anominal\"n\n" +
	"\x10TransferResponse\x12!\n" +
	"\ftransaksi_id\x18\x01 \x01(\tR\vtransaksiId\x12\x1d\n" +
	"\n" +
	"sisa_saldo\x18\x02 \x01(\x03R\tsisaSaldo\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"U\n" +
	"\bGajiItem\x12&\n" +
	"\x0fno_rek_karyawan\x18\x01 \x01(\tR\rnoRekKaryawan\x12!\n" +
	"\fnominal_gaji\x18\x02 \x01(\x03R\vnominalGaji\"\xcd\x01\n" +
	"\x17BatchDepositGajiRequest\x12*\n" +
	"\x11no_rek_perusahaan\x18\x01 \x01(\tR\x0fnoRekPerusahaan\x12'\n" +
	"\x0fnama_perusahaan\x18\x02 \x01(\tR\x0enamaPerusahaan\x12%\n" +
	"\x0epin_perusahaan\x18\x03 \x01(\tR\rpinPerusahaan\x126\n" +
	"\vdaftar_gaji\x18\x04 \x03(\v2\x15.transaction.GajiItemR\n" +
	"daftarGaji\"\x9f\x01\n" +
	"\x18BatchDepositGajiResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12%\n" +
	"\x0etotal_diproses\x18\x02 \x01(\x05R\rtotalDiproses\x12*\n" +
	"\x11total_dana_keluar\x18\x03 \x01(\x03R\x0ftotalDanaKeluar\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage2\xec\x02\n" +
	"\x12TransactionService\x12P\n" +
	"\vCashDeposit\x12\x1f.transaction.CashDepositRequest\x1a .transaction.CashDepositResponse\x12Y\n" +
	"\x0eCashWithdrawal\x12\".transaction.CashWithdrawalRequest\x1a#.transaction.CashWithdrawalResponse\x12H\n" +
	"\tTransafer\x12\x1c.transaction.TransferRequest\x1a\x1d.transaction.TransferResponse\x12_\n" +
	"\x10BatchDepositGaji\x12$.transaction.BatchDepositGajiRequest\x1a%.transaction.BatchDepositGajiResponseB\x12Z\x10./;transactionpbb\x06proto3"

var (
	file_transaction_proto_rawDescOnce sync.Once
	file_transaction_proto_rawDescData []byte
)

func file_transaction_proto_rawDescGZIP() []byte {
	file_transaction_proto_rawDescOnce.Do(func() {
		file_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)))
	})
	return file_transaction_proto_rawDescData
}

var file_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_transaction_proto_goTypes = []any{
	(*CashDepositRequest)(nil),       // 0: transaction.CashDepositRequest
	(*CashDepositResponse)(nil),      // 1: transaction.CashDepositResponse
	(*CashWithdrawalRequest)(nil),    // 2: transaction.CashWithdrawalRequest
	(*CashWithdrawalResponse)(nil),   // 3: transaction.CashWithdrawalResponse
	(*TransferRequest)(nil),          // 4: transaction.TransferRequest
	(*TransferResponse)(nil),         // 5: transaction.TransferResponse
	(*GajiItem)(nil),                 // 6: transaction.GajiItem
	(*BatchDepositGajiRequest)(nil),  // 7: transaction.BatchDepositGajiRequest
	(*BatchDepositGajiResponse)(nil), // 8: transaction.BatchDepositGajiResponse
}
var file_transaction_proto_depIdxs = []int32{
	6, // 0: transaction.BatchDepositGajiRequest.daftar_gaji:type_name -> transaction.GajiItem
	0, // 1: transaction.TransactionService.CashDeposit:input_type -> transaction.CashDepositRequest
	2, // 2: transaction.TransactionService.CashWithdrawal:input_type -> transaction.CashWithdrawalRequest
	4, // 3: transaction.TransactionService.Transafer:input_type -> transaction.TransferRequest
	7, // 4: transaction.TransactionService.BatchDepositGaji:input_type -> transaction.BatchDepositGajiRequest
	1, // 5: transaction.TransactionService.CashDeposit:output_type -> transaction.CashDepositResponse
	3, // 6: transaction.TransactionService.CashWithdrawal:output_type -> transaction.CashWithdrawalResponse
	5, // 7: transaction.TransactionService.Transafer:output_type -> transaction.TransferResponse
	8, // 8: transaction.TransactionService.BatchDepositGaji:output_type -> transaction.BatchDepositGajiResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_transaction_proto_init() }
func file_transaction_proto_init() {
	if File_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_proto_goTypes,
		DependencyIndexes: file_transaction_proto_depIdxs,
		MessageInfos:      file_transaction_proto_msgTypes,
	}.Build()
	File_transaction_proto = out.File
	file_transaction_proto_goTypes = nil
	file_transaction_proto_depIdxs = nil
}
