// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: transaction.proto

package transactionpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransactionService_CashDeposit_FullMethodName      = "/transaction.TransactionService/CashDeposit"
	TransactionService_CashWithdrawal_FullMethodName   = "/transaction.TransactionService/CashWithdrawal"
	TransactionService_Transafer_FullMethodName        = "/transaction.TransactionService/Transafer"
	TransactionService_BatchDepositGaji_FullMethodName = "/transaction.TransactionService/BatchDepositGaji"
)

// TransactionServiceClient is the client API for TransactionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionServiceClient interface {
	CashDeposit(ctx context.Context, in *CashDepositRequest, opts ...grpc.CallOption) (*CashDepositResponse, error)
	CashWithdrawal(ctx context.Context, in *CashWithdrawalRequest, opts ...grpc.CallOption) (*CashWithdrawalResponse, error)
	Transafer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error)
	BatchDepositGaji(ctx context.Context, in *BatchDepositGajiRequest, opts ...grpc.CallOption) (*BatchDepositGajiResponse, error)
}

type transactionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionServiceClient(cc grpc.ClientConnInterface) TransactionServiceClient {
	return &transactionServiceClient{cc}
}

func (c *transactionServiceClient) CashDeposit(ctx context.Context, in *CashDepositRequest, opts ...grpc.CallOption) (*CashDepositResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CashDepositResponse)
	err := c.cc.Invoke(ctx, TransactionService_CashDeposit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) CashWithdrawal(ctx context.Context, in *CashWithdrawalRequest, opts ...grpc.CallOption) (*CashWithdrawalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CashWithdrawalResponse)
	err := c.cc.Invoke(ctx, TransactionService_CashWithdrawal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) Transafer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferResponse)
	err := c.cc.Invoke(ctx, TransactionService_Transafer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) BatchDepositGaji(ctx context.Context, in *BatchDepositGajiRequest, opts ...grpc.CallOption) (*BatchDepositGajiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchDepositGajiResponse)
	err := c.cc.Invoke(ctx, TransactionService_BatchDepositGaji_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionServiceServer is the server API for TransactionService service.
// All implementations must embed UnimplementedTransactionServiceServer
// for forward compatibility.
type TransactionServiceServer interface {
	CashDeposit(context.Context, *CashDepositRequest) (*CashDepositResponse, error)
	CashWithdrawal(context.Context, *CashWithdrawalRequest) (*CashWithdrawalResponse, error)
	Transafer(context.Context, *TransferRequest) (*TransferResponse, error)
	BatchDepositGaji(context.Context, *BatchDepositGajiRequest) (*BatchDepositGajiResponse, error)
	mustEmbedUnimplementedTransactionServiceServer()
}

// UnimplementedTransactionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransactionServiceServer struct{}

func (UnimplementedTransactionServiceServer) CashDeposit(context.Context, *CashDepositRequest) (*CashDepositResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CashDeposit not implemented")
}
func (UnimplementedTransactionServiceServer) CashWithdrawal(context.Context, *CashWithdrawalRequest) (*CashWithdrawalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CashWithdrawal not implemented")
}
func (UnimplementedTransactionServiceServer) Transafer(context.Context, *TransferRequest) (*TransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Transafer not implemented")
}
func (UnimplementedTransactionServiceServer) BatchDepositGaji(context.Context, *BatchDepositGajiRequest) (*BatchDepositGajiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchDepositGaji not implemented")
}
func (UnimplementedTransactionServiceServer) mustEmbedUnimplementedTransactionServiceServer() {}
func (UnimplementedTransactionServiceServer) testEmbeddedByValue()                            {}

// UnsafeTransactionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionServiceServer will
// result in compilation errors.
type UnsafeTransactionServiceServer interface {
	mustEmbedUnimplementedTransactionServiceServer()
}

func RegisterTransactionServiceServer(s grpc.ServiceRegistrar, srv TransactionServiceServer) {
	// If the following call panics, it indicates UnimplementedTransactionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransactionService_ServiceDesc, srv)
}

func _TransactionService_CashDeposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CashDepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).CashDeposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_CashDeposit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).CashDeposit(ctx, req.(*CashDepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_CashWithdrawal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CashWithdrawalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).CashWithdrawal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_CashWithdrawal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).CashWithdrawal(ctx, req.(*CashWithdrawalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_Transafer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).Transafer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_Transafer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).Transafer(ctx, req.(*TransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_BatchDepositGaji_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDepositGajiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).BatchDepositGaji(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_BatchDepositGaji_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).BatchDepositGaji(ctx, req.(*BatchDepositGajiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionService_ServiceDesc is the grpc.ServiceDesc for TransactionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transaction.TransactionService",
	HandlerType: (*TransactionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CashDeposit",
			Handler:    _TransactionService_CashDeposit_Handler,
		},
		{
			MethodName: "CashWithdrawal",
			Handler:    _TransactionService_CashWithdrawal_Handler,
		},
		{
			MethodName: "Transafer",
			Handler:    _TransactionService_Transafer_Handler,
		},
		{
			MethodName: "BatchDepositGaji",
			Handler:    _TransactionService_BatchDepositGaji_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction.proto",
}
